name: CI
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./01 Starting Project"

    steps:
      - uses: actions/checkout@v3

      - run: npm install
      - run: npm run test
      - run: npm run build

      - run: echo "Deploying..."
