name: CI
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: List files
        run: |
          pwd
          ls -la
          find . -name package.json
